#!/usr/bin/env python3
"""Encode the original PNG as embedded GX RGB565 blocks and mipmaps.

Developer-only dependency: Pillow. Builds use the checked-in header, so no
image tooling or game assets are required on any target platform.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SIZE, LAST_MIP = 256, 6  # Stop at one complete 4x4 GX block.


def encode():
    with Image.open(ROOT / 'art/pedestal/charcoal-stone.png') as source:
        image = source.convert('RGB').resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    data = bytearray()
    for level in range(LAST_MIP + 1):
        size = SIZE >> level
        mip = image.resize((size, size), Image.Resampling.LANCZOS)
        # GX RGB565 is big-endian, tiled in 4x4 blocks on every host platform.
        for by in range(0, size, 4):
            for bx in range(0, size, 4):
                for y in range(by, by + 4):
                    for x in range(bx, bx + 4):
                        r, g, b = mip.getpixel((x, y))
                        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
                        data.extend(value.to_bytes(2, 'big'))
    assert len(data) == sum((SIZE >> i) ** 2 * 2 for i in range(LAST_MIP + 1))
    header = '// Generated by tools/generate_pedestal_texture.py; do not edit.\n'
    header += '// Original Dawnlight stone; provenance: art/pedestal/README.md.\n'
    header += '#pragma once\n\nnamespace dawnlight::pedestal_art {\n'
    header += f'inline constexpr unsigned kSize = {SIZE}, kLastMip = {LAST_MIP};\n'
    header += 'alignas(32) inline constexpr unsigned char kPixels[] = {\n'
    header += ''.join('    ' + ','.join(f'0x{n:02x}' for n in data[i:i+24]) + ',\n'
                      for i in range(0, len(data), 24))
    header += '};\n} // namespace dawnlight::pedestal_art\n'
    (ROOT / 'src/generated/pedestal_stone.hpp').write_text(header)
    print(f'Pedestal stone: {len(data)} bytes, {LAST_MIP + 1} mip levels')


if __name__ == '__main__':
    encode()
