#!/usr/bin/env python3
"""Retarget grounded combat footwork from a user-supplied KN_a.arc.

Run with NumPy/SciPy installed. Only additive leg rotations are exported.
Root travel, upper body, airborne poses and native animation timing stay native.
"""
import argparse
import tempfile
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
import generate_shade_stride as rig

# Native animation-table order, not motion-sequence IDs.
CLIPS = ('wait_a step step_ikaku talk_a fight_a defense damage damage_s '
         'damage_s_wait defense_s_s defense_s_l defense_s_e magic fry land '
         'laydown porked porked_wait dead getup stepl roll cut fry_m land_m '
         'laydown_m getup_m demo_kamae kabuto kabuto_wait wait_b talk_b iai '
         'iai_wait daijump').split()
JOINTS = [25, 26, 27, 29, 30, 31]
SAMPLES_PER_FRAME = 4


def smooth(x):
    x = np.clip(x, 0, 1)
    return x*x*(3-2*x)


def retarget(local, joints):
    """Widen support and stride; solve both legs with unchanged bone lengths.

    Corrections fade out with foot height and pelvis tilt, so rolls, knockdowns
    and aerial attacks retain their original choreography. Keeping the foot's
    world orientation also preserves heel/toe pitch during push-off and landing.
    """
    rig.JOINTS = joints
    mats = rig.sample_mats(local)
    out = local.copy()
    center = (mats[27, :3, 3] + mats[31, :3, 3]) / 2
    # The exported waist bone points downward along local +X.
    upright = smooth((-mats[22, 1, 0] - .3) / .5)
    for hip, knee, foot, toe, side, offset in rig.LEGS:
        ankle = mats[foot, :3, 3]
        weight = upright * (1-smooth((ankle[1]-24)/32))
        if weight < 1e-8:
            continue
        target = ankle.copy()
        target[[0, 2]] += (ankle-center)[[0, 2]] * [.14, .24] * weight
        h = mats[hip, :3, 3]
        l1, l2 = np.linalg.norm(local[knee, 2]), np.linalg.norm(local[foot, 2])
        # Keep the ankle on its source contact plane even near full extension.
        delta = target-h
        reach = max(l1+l2-.25, np.linalg.norm(ankle-h))
        horizontal = np.linalg.norm(delta[[0, 2]])
        available = np.sqrt(max(0, reach*reach-delta[1]*delta[1]))
        if horizontal > available:
            target[[0, 2]] = h[[0, 2]] + delta[[0, 2]] * available/horizontal
        delta = target-h
        dist = np.linalg.norm(delta)
        direction = delta/dist
        along = (l1*l1-l2*l2+dist*dist)/(2*dist)
        height = np.sqrt(max(0, l1*l1-along*along))
        # Follow the native knee plane, including sideways and turning attacks.
        pole = mats[knee, :3, 3]-h
        pole -= direction*np.dot(pole, direction)
        if np.linalg.norm(pole) < 1e-6:
            continue
        k = h+along*direction+height*pole/np.linalg.norm(pole)
        world_hip = rig.rot_between(mats[hip, :3, :3]@local[knee, 2], k-h)@mats[hip, :3, :3]
        world_knee = rig.rot_between(mats[knee, :3, :3]@local[foot, 2], target-k)@mats[knee, :3, :3]
        parent = mats[joints[hip]['parent'], :3, :3]
        out[hip, 1] = Rotation.from_matrix(parent.T@world_hip).as_euler('xyz')
        out[knee, 1] = Rotation.from_matrix(world_hip.T@world_knee).as_euler('xyz')
        out[foot, 1] = Rotation.from_matrix(world_knee.T@mats[foot, :3, :3]).as_euler('xyz')
    return out


def generate(archive, output):
    with tempfile.TemporaryDirectory() as tmp:
        rig.ROOT = Path(tmp)
        rig.extract(archive)
        joints = rig.skeleton()
        rows = ['// Generated by tools/generate_shade_combat.py; additive leg rotations only.',
                '#pragma once', '#include <cstdint>',
                'namespace dawnlight::shade::combat_pose {',
                f'inline constexpr int samples_per_frame = {SAMPLES_PER_FRAME};',
                'struct Clip { int frames; bool loop; const std::int16_t (*delta)[6][4]; };']
        metadata = []
        max_height_error = 0
        for idx, name in enumerate(CLIPS):
            anim = rig.Bck(rig.ROOT/f'kn_{name}.bck')
            assert anim.count == 37
            # Walking already has its own authored gait. Talk/death poses still
            # get the transition layer but no stance expansion.
            enabled = idx not in (1, 2, 3, 15, 16, 17, 18, 25, 31)
            if not enabled:
                metadata.append(f'    {{{anim.frames}, {str(anim.b[8]==2).lower()}, nullptr}},')
                continue
            rows.append(f'inline constexpr std::int16_t clip_{idx}[{anim.frames*SAMPLES_PER_FRAME+1}][6][4] = {{')
            for sample in range(anim.frames*SAMPLES_PER_FRAME+1):
                t = sample/SAMPLES_PER_FRAME
                source = np.array([anim.sample(j, t) for j in range(37)])
                authored = retarget(source, joints)
                original_mats, new_mats = rig.sample_mats(source), rig.sample_mats(authored)
                for hip, knee, foot, toe, _, _ in rig.LEGS:
                    max_height_error = max(max_height_error, abs(new_mats[foot, 1, 3]-original_mats[foot, 1, 3]))
                    assert np.linalg.norm(new_mats[foot, :3, :3]-original_mats[foot, :3, :3]) < 1e-5
                    for a, b in ((hip, knee), (knee, foot)):
                        assert abs(np.linalg.norm(new_mats[b, :3, 3]-new_mats[a, :3, 3])-np.linalg.norm(source[b, 2])) < 1e-5
                delta = (Rotation.from_euler('xyz', authored[JOINTS, 1]) *
                         Rotation.from_euler('xyz', source[JOINTS, 1]).inv()).as_quat()
                delta *= np.where(delta[:, 3:] < 0, -1, 1)
                values = np.rint(delta*32767).astype(int)
                rows.append('    {'+', '.join('{'+', '.join(map(str,v))+'}' for v in values)+'},')
            rows.append('};')
            metadata.append(f'    {{{anim.frames}, {str(anim.b[8]==2).lower()}, clip_{idx}}},')
        assert max_height_error < 1e-5, max_height_error
        rows += ['inline constexpr Clip clips[] = {']+metadata+['};', '} // namespace dawnlight::shade::combat_pose', '']
        Path(output).write_text('\n'.join(rows))
        print(f'{len(CLIPS)} clips: fixed bone lengths, foot orientation and contact height verified (max error {max_height_error:.8f}).')


if __name__ == '__main__':
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument('archive', type=Path)
    cli.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1]/'src/generated/shade_combat.hpp')
    args = cli.parse_args()
    generate(args.archive, args.output)
